### ISSUE TITLE
`require` does not recognice libs from Crystal SDK

### ISSUE THREAD

**Issue by MarioAriasC** [asedunov/intellij-crystal-lang#1]
```crystal
require "./benchmarks"
require "./objects"
require "./symbols"
require "./lexer"
require "option_parser"
```

It shows `Cannot resolve file 'option_parser.cr'` but `option_parser` comes from the Crystal SDK

If you want to check, you can use my project https://github.com/MarioAriasC/monyet/blob/main/src/monyet.cr

Cheers

**Comment by asedunov** [comment]
Thanks! SDK support is the priority task together with adding language changes from 1.3.0
