### ISSUE TITLE
Add "Choose partial declaration" option for classes and modules

### ISSUE THREAD

**Issue by watzon** [asedunov/intellij-crystal-lang#43]
In Ruby you get this little icon off to the side of classes and modules which have definitions that are split across multiple files
![image](https://user-images.githubusercontent.com/4535422/225959048-8255138b-52fb-4313-bfc2-d071e7aeae44.png)

Clicking it reveals a list of files containing a partial declaration for that module
![image](https://user-images.githubusercontent.com/4535422/225959231-14e77ed5-bb4e-4795-84eb-8a5edc5e2cd6.png)

**Comment by asedunov** [comment]
Thanks! I'll include this feature to upcoming release

**Comment by watzon** [comment]
Wow that was quick

**Comment by asedunov** [comment]
Yeah, in this case it was pretty easy as I'd already implemented necessary semantic information a while ago - it just wasn't used for line markers themselves
